### Necessary Imports

In [1]:
import pandas as pd
import os

In [2]:
benin = pd.read_csv("Benin.csv")
benin

,water_source,time_to_water,toilet,Electricity,Radio,Television,Fridge,Bicycle,Motorbike,Car,floor,U1_R2,HHID,countrycode,cluster_number,household_number,Year
0,32,10,31,1,1,0,0,0,0,0,34,2,1 3,BJ7,1,3,2018
1,32,10,31,0,1,0,0,1,1,0,34,2,1 9,BJ7,1,9,2018
2,32,5,31,1,1,1,0,0,1,0,34,2,1 15,BJ7,1,15,2018
3,32,20,31,0,1,0,0,0,1,0,11,2,1 21,BJ7,1,21,2018
4,32,15,31,0,1,0,0,1,0,0,11,2,1 27,BJ7,1,27,2018
5,32,10,31,1,1,0,0,1,1,0,34,2,1 33,BJ7,1,33,2018
6,32,996,31,0,1,0,0,1,1,0,34,2,1 39,BJ7,1,39,2018
7,32,15,31,1,1,0,0,1,1,0,11,2,1 46,BJ7,1,46,2018
8,32,996,31,0,1,0,0,1,1,0,11,2,1 52,BJ7,1,52,2018
9,32,20,31,1,1,0,0,1,1,0,34,2,1 58,BJ7,1,58,2018
10,32,996,31,0,0,0,0,0,0,0,34,2,1 64,BJ7,1,64,2018
11,32,10,31,0,1,0,0,0,1,0,11,2,1 70,BJ7,1,70,2018
12,32,15,31,0,1,0,0,1,1,0,34,2,1 76,BJ7,1,76,2018
13,32,45,31,1,1,0,0,1,1,0,11,2,1 82,BJ7,1,82,2018
14,32,996,31,0,1,0,0,1,1,0,11,2,1 88,BJ7,1,88,2018
15,32,15,31,0,1,0,0,1,0,0,11,2,1 94,BJ7,1,94,2018
16,32,5,31,0,1,0,0,0,0,0,34,2,1 101,BJ7,1,101,2018
17,31,5,31,1,1,1,0,1,1,0,34,2,1 107,BJ7,1,107,2018
18,32,10,31,0,1,0,0,0,1,0,11,2,1 113,BJ7,1,113,2018
19,14,25,31,1,1,0,0,0,1,0,34,2,1 119,BJ7,1,119,2018
20,32,10,31,0,1,0,0,0,1,0,34,2,1 125,BJ7,1,125,2018
21,31,15,31,0,1,0,0,0,0,0,11,2,1 131,BJ7,1,131,2018
22,21,10,31,0,1,0,0,0,1,0,34,2,1 137,BJ7,1,137,2018
23,14,30,31,1,1,0,0,1,1,0,34,2,1 143,BJ7,1,143,2018
24,43,5,31,0,1,0,0,0,1,0,34,2,1 149,BJ7,1,149,2018
25,21,30,31,1,1,0,0,1,1,0,31,2,1 156,BJ7,1,156,2018
26,32,10,31,0,1,0,0,0,1,0,34,2,2 2,BJ7,2,2,2018
27,32,45,31,0,1,0,0,0,0,0,11,2,2 7,BJ7,2,7,2018
28,32,30,31,0,0,0,0,1,0,0,11,2,2 13,BJ7,2,13,2018
29,32,10,31,0,1,0,0,1,0,0,11,2,2 19,BJ7,2,19,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14126,21,60,31,0,1,1,0,0,1,0,34,2,554 108,BJ7,554,108,2017
14127,21,13,31,0,0,0,0,0,0,0,11,2,554 113,BJ7,554,113,2017
14128,21,120,23,0,1,0,0,1,1,0,11,2,554 118,BJ7,554,118,2017
14129,21,20,31,0,1,0,0,0,1,0,11,2,554 123,BJ7,554,123,2017
14130,21,60,31,0,1,0,0,0,1,0,34,2,554 128,BJ7,554,128,2017
14131,13,996,21,1,1,1,0,0,1,0,34,1,555 4,BJ7,555,4,2017
14132,21,15,22,1,1,1,0,0,1,0,34,1,555 11,BJ7,555,11,2017
14133,21,30,31,0,1,0,0,0,1,0,34,1,555 18,BJ7,555,18,2017
14134,21,60,21,0,1,1,0,0,1,0,34,1,555 25,BJ7,555,25,2017
14135,21,20,23,1,0,0,0,0,1,0,34,1,555 32,BJ7,555,32,2017
14136,21,60,31,0,1,0,0,0,0,0,34,1,555 39,BJ7,555,39,2017
14137,21,40,22,1,1,1,0,0,1,0,34,1,555 47,BJ7,555,47,2017
14138,21,5,21,1,1,0,0,0,1,0,34,1,555 54,BJ7,555,54,2017
14139,21,10,21,0,0,0,0,0,0,0,34,1,555 61,BJ7,555,61,2017
14140,21,10,21,1,1,1,0,0,0,0,34,1,555 68,BJ7,555,68,2017
14141,62,996,22,1,1,1,0,0,1,0,34,1,555 75,BJ7,555,75,2017
14142,21,120,23,1,1,1,0,0,1,0,34,1,555 82,BJ7,555,82,2017
14143,13,996,22,1,1,1,0,0,1,0,34,1,555 90,BJ7,555,90,2017
14144,13,996,12,1,1,1,1,1,1,1,33,1,555 97,BJ7,555,97,2017
14145,21,30,22,1,1,0,0,0,0,0,34,1,555 104,BJ7,555,104,2017
14146,21,120,23,1,0,1,0,1,1,0,35,1,555 111,BJ7,555,111,2017
14147,13,996,22,1,1,1,0,0,1,0,34,1,555 118,BJ7,555,118,2017
14148,32,996,31,0,1,1,0,0,1,0,11,1,555 132,BJ7,555,132,2017
14149,14,30,31,1,1,1,0,0,1,0,34,1,555 140,BJ7,555,140,2017
14150,13,996,22,1,1,1,0,0,1,0,34,1,555 147,BJ7,555,147,2017
14151,13,996,21,1,1,1,1,0,1,0,34,1,555 154,BJ7,555,154,2017
14152,62,5,22,1,1,1,0,0,1,0,34,1,555 161,BJ7,555,161,2017
14153,13,996,21,1,0,0,0,0,0,0,34,1,555 168,BJ7,555,168,2017
14154,32,996,23,1,1,1,0,0,1,0,34,1,555 175,BJ7,555,175,2017
14155,21,10,31,1,1,0,0,0,1,0,34,1,555 183,BJ7,555,183,2017

### Checking the unique values in the columns that need to be changed

In [16]:
benin['water_source'].value_counts()

21    4094
32    2770
13    2062
14    1764
43     888
11     777
12     682
31     603
42     169
51      41
62      38
41      35
61      31
71      10
Name: water_source, dtype: int64

In [5]:
benin.drop(['time_to_water'], axis=1,inplace=True)

In [15]:
benin['toilet'].value_counts()

31    7619
22    2578
21    1378
23    1341
12     718
13     168
43     118
41      15
11      11
14      10
15       6
42       2
Name: toilet, dtype: int64

In [7]:
benin['floor'].value_counts()

34    8870
11    4140
33     665
12     134
21      86
35      85
22      79
31      51
96      26
32      20
Name: floor, dtype: int64

### Dropping the rows that contain missing values

In [13]:
to_drop = benin[ (benin['water_source'] == 96) | (benin['toilet'] == 96) | (benin['floor'] == 96)].index
to_drop2 = benin[ benin['toilet'] == 13 ].index
to_drop3 = benin[ benin['water_source'] == 72 ].index

In [18]:
benin.drop(to_drop3, inplace = True)
benin

,water_source,toilet,Electricity,Radio,Television,Fridge,Bicycle,Motorbike,Car,floor,U1_R2,HHID,countrycode,cluster_number,household_number,Year
0,32,31,1,1,0,0,0,0,0,34,2,1 3,BJ7,1,3,2018
1,32,31,0,1,0,0,1,1,0,34,2,1 9,BJ7,1,9,2018
2,32,31,1,1,1,0,0,1,0,34,2,1 15,BJ7,1,15,2018
3,32,31,0,1,0,0,0,1,0,11,2,1 21,BJ7,1,21,2018
4,32,31,0,1,0,0,1,0,0,11,2,1 27,BJ7,1,27,2018
5,32,31,1,1,0,0,1,1,0,34,2,1 33,BJ7,1,33,2018
6,32,31,0,1,0,0,1,1,0,34,2,1 39,BJ7,1,39,2018
7,32,31,1,1,0,0,1,1,0,11,2,1 46,BJ7,1,46,2018
8,32,31,0,1,0,0,1,1,0,11,2,1 52,BJ7,1,52,2018
9,32,31,1,1,0,0,1,1,0,34,2,1 58,BJ7,1,58,2018
10,32,31,0,0,0,0,0,0,0,34,2,1 64,BJ7,1,64,2018
11,32,31,0,1,0,0,0,1,0,11,2,1 70,BJ7,1,70,2018
12,32,31,0,1,0,0,1,1,0,34,2,1 76,BJ7,1,76,2018
13,32,31,1,1,0,0,1,1,0,11,2,1 82,BJ7,1,82,2018
14,32,31,0,1,0,0,1,1,0,11,2,1 88,BJ7,1,88,2018
15,32,31,0,1,0,0,1,0,0,11,2,1 94,BJ7,1,94,2018
16,32,31,0,1,0,0,0,0,0,34,2,1 101,BJ7,1,101,2018
17,31,31,1,1,1,0,1,1,0,34,2,1 107,BJ7,1,107,2018
18,32,31,0,1,0,0,0,1,0,11,2,1 113,BJ7,1,113,2018
19,14,31,1,1,0,0,0,1,0,34,2,1 119,BJ7,1,119,2018
20,32,31,0,1,0,0,0,1,0,34,2,1 125,BJ7,1,125,2018
21,31,31,0,1,0,0,0,0,0,11,2,1 131,BJ7,1,131,2018
22,21,31,0,1,0,0,0,1,0,34,2,1 137,BJ7,1,137,2018
23,14,31,1,1,0,0,1,1,0,34,2,1 143,BJ7,1,143,2018
24,43,31,0,1,0,0,0,1,0,34,2,1 149,BJ7,1,149,2018
25,21,31,1,1,0,0,1,1,0,31,2,1 156,BJ7,1,156,2018
26,32,31,0,1,0,0,0,1,0,34,2,2 2,BJ7,2,2,2018
27,32,31,0,1,0,0,0,0,0,11,2,2 7,BJ7,2,7,2018
28,32,31,0,0,0,0,1,0,0,11,2,2 13,BJ7,2,13,2018
29,32,31,0,1,0,0,1,0,0,11,2,2 19,BJ7,2,19,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14126,21,31,0,1,1,0,0,1,0,34,2,554 108,BJ7,554,108,2017
14127,21,31,0,0,0,0,0,0,0,11,2,554 113,BJ7,554,113,2017
14128,21,23,0,1,0,0,1,1,0,11,2,554 118,BJ7,554,118,2017
14129,21,31,0,1,0,0,0,1,0,11,2,554 123,BJ7,554,123,2017
14130,21,31,0,1,0,0,0,1,0,34,2,554 128,BJ7,554,128,2017
14131,13,21,1,1,1,0,0,1,0,34,1,555 4,BJ7,555,4,2017
14132,21,22,1,1,1,0,0,1,0,34,1,555 11,BJ7,555,11,2017
14133,21,31,0,1,0,0,0,1,0,34,1,555 18,BJ7,555,18,2017
14134,21,21,0,1,1,0,0,1,0,34,1,555 25,BJ7,555,25,2017
14135,21,23,1,0,0,0,0,1,0,34,1,555 32,BJ7,555,32,2017
14136,21,31,0,1,0,0,0,0,0,34,1,555 39,BJ7,555,39,2017
14137,21,22,1,1,1,0,0,1,0,34,1,555 47,BJ7,555,47,2017
14138,21,21,1,1,0,0,0,1,0,34,1,555 54,BJ7,555,54,2017
14139,21,21,0,0,0,0,0,0,0,34,1,555 61,BJ7,555,61,2017
14140,21,21,1,1,1,0,0,0,0,34,1,555 68,BJ7,555,68,2017
14141,62,22,1,1,1,0,0,1,0,34,1,555 75,BJ7,555,75,2017
14142,21,23,1,1,1,0,0,1,0,34,1,555 82,BJ7,555,82,2017
14143,13,22,1,1,1,0,0,1,0,34,1,555 90,BJ7,555,90,2017
14144,13,12,1,1,1,1,1,1,1,33,1,555 97,BJ7,555,97,2017
14145,21,22,1,1,0,0,0,0,0,34,1,555 104,BJ7,555,104,2017
14146,21,23,1,0,1,0,1,1,0,35,1,555 111,BJ7,555,111,2017
14147,13,22,1,1,1,0,0,1,0,34,1,555 118,BJ7,555,118,2017
14148,32,31,0,1,1,0,0,1,0,11,1,555 132,BJ7,555,132,2017
14149,14,31,1,1,1,0,0,1,0,34,1,555 140,BJ7,555,140,2017
14150,13,22,1,1,1,0,0,1,0,34,1,555 147,BJ7,555,147,2017
14151,13,21,1,1,1,1,0,1,0,34,1,555 154,BJ7,555,154,2017
14152,62,22,1,1,1,0,0,1,0,34,1,555 161,BJ7,555,161,2017
14153,13,21,1,0,0,0,0,0,0,34,1,555 168,BJ7,555,168,2017
14154,32,23,1,1,1,0,0,1,0,34,1,555 175,BJ7,555,175,2017
14155,21,31,1,1,0,0,0,1,0,34,1,555 183,BJ7,555,183,2017

### Replacing the codes for toilet / water source quality with binary codes

In [19]:
benin['toilet'] = benin['toilet'].replace([10,11,12,14,15,20,21,22], 1)

In [20]:
benin['toilet'] = benin['toilet'].replace([23,30,31,41,42,43], 0)

In [21]:
benin

,water_source,toilet,Electricity,Radio,Television,Fridge,Bicycle,Motorbike,Car,floor,U1_R2,HHID,countrycode,cluster_number,household_number,Year
0,32,0,1,1,0,0,0,0,0,34,2,1 3,BJ7,1,3,2018
1,32,0,0,1,0,0,1,1,0,34,2,1 9,BJ7,1,9,2018
2,32,0,1,1,1,0,0,1,0,34,2,1 15,BJ7,1,15,2018
3,32,0,0,1,0,0,0,1,0,11,2,1 21,BJ7,1,21,2018
4,32,0,0,1,0,0,1,0,0,11,2,1 27,BJ7,1,27,2018
5,32,0,1,1,0,0,1,1,0,34,2,1 33,BJ7,1,33,2018
6,32,0,0,1,0,0,1,1,0,34,2,1 39,BJ7,1,39,2018
7,32,0,1,1,0,0,1,1,0,11,2,1 46,BJ7,1,46,2018
8,32,0,0,1,0,0,1,1,0,11,2,1 52,BJ7,1,52,2018
9,32,0,1,1,0,0,1,1,0,34,2,1 58,BJ7,1,58,2018
10,32,0,0,0,0,0,0,0,0,34,2,1 64,BJ7,1,64,2018
11,32,0,0,1,0,0,0,1,0,11,2,1 70,BJ7,1,70,2018
12,32,0,0,1,0,0,1,1,0,34,2,1 76,BJ7,1,76,2018
13,32,0,1,1,0,0,1,1,0,11,2,1 82,BJ7,1,82,2018
14,32,0,0,1,0,0,1,1,0,11,2,1 88,BJ7,1,88,2018
15,32,0,0,1,0,0,1,0,0,11,2,1 94,BJ7,1,94,2018
16,32,0,0,1,0,0,0,0,0,34,2,1 101,BJ7,1,101,2018
17,31,0,1,1,1,0,1,1,0,34,2,1 107,BJ7,1,107,2018
18,32,0,0,1,0,0,0,1,0,11,2,1 113,BJ7,1,113,2018
19,14,0,1,1,0,0,0,1,0,34,2,1 119,BJ7,1,119,2018
20,32,0,0,1,0,0,0,1,0,34,2,1 125,BJ7,1,125,2018
21,31,0,0,1,0,0,0,0,0,11,2,1 131,BJ7,1,131,2018
22,21,0,0,1,0,0,0,1,0,34,2,1 137,BJ7,1,137,2018
23,14,0,1,1,0,0,1,1,0,34,2,1 143,BJ7,1,143,2018
24,43,0,0,1,0,0,0,1,0,34,2,1 149,BJ7,1,149,2018
25,21,0,1,1,0,0,1,1,0,31,2,1 156,BJ7,1,156,2018
26,32,0,0,1,0,0,0,1,0,34,2,2 2,BJ7,2,2,2018
27,32,0,0,1,0,0,0,0,0,11,2,2 7,BJ7,2,7,2018
28,32,0,0,0,0,0,1,0,0,11,2,2 13,BJ7,2,13,2018
29,32,0,0,1,0,0,1,0,0,11,2,2 19,BJ7,2,19,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14126,21,0,0,1,1,0,0,1,0,34,2,554 108,BJ7,554,108,2017
14127,21,0,0,0,0,0,0,0,0,11,2,554 113,BJ7,554,113,2017
14128,21,0,0,1,0,0,1,1,0,11,2,554 118,BJ7,554,118,2017
14129,21,0,0,1,0,0,0,1,0,11,2,554 123,BJ7,554,123,2017
14130,21,0,0,1,0,0,0,1,0,34,2,554 128,BJ7,554,128,2017
14131,13,1,1,1,1,0,0,1,0,34,1,555 4,BJ7,555,4,2017
14132,21,1,1,1,1,0,0,1,0,34,1,555 11,BJ7,555,11,2017
14133,21,0,0,1,0,0,0,1,0,34,1,555 18,BJ7,555,18,2017
14134,21,1,0,1,1,0,0,1,0,34,1,555 25,BJ7,555,25,2017
14135,21,0,1,0,0,0,0,1,0,34,1,555 32,BJ7,555,32,2017
14136,21,0,0,1,0,0,0,0,0,34,1,555 39,BJ7,555,39,2017
14137,21,1,1,1,1,0,0,1,0,34,1,555 47,BJ7,555,47,2017
14138,21,1,1,1,0,0,0,1,0,34,1,555 54,BJ7,555,54,2017
14139,21,1,0,0,0,0,0,0,0,34,1,555 61,BJ7,555,61,2017
14140,21,1,1,1,1,0,0,0,0,34,1,555 68,BJ7,555,68,2017
14141,62,1,1,1,1,0,0,1,0,34,1,555 75,BJ7,555,75,2017
14142,21,0,1,1,1,0,0,1,0,34,1,555 82,BJ7,555,82,2017
14143,13,1,1,1,1,0,0,1,0,34,1,555 90,BJ7,555,90,2017
14144,13,1,1,1,1,1,1,1,1,33,1,555 97,BJ7,555,97,2017
14145,21,1,1,1,0,0,0,0,0,34,1,555 104,BJ7,555,104,2017
14146,21,0,1,0,1,0,1,1,0,35,1,555 111,BJ7,555,111,2017
14147,13,1,1,1,1,0,0,1,0,34,1,555 118,BJ7,555,118,2017
14148,32,0,0,1,1,0,0,1,0,11,1,555 132,BJ7,555,132,2017
14149,14,0,1,1,1,0,0,1,0,34,1,555 140,BJ7,555,140,2017
14150,13,1,1,1,1,0,0,1,0,34,1,555 147,BJ7,555,147,2017
14151,13,1,1,1,1,1,0,1,0,34,1,555 154,BJ7,555,154,2017
14152,62,1,1,1,1,0,0,1,0,34,1,555 161,BJ7,555,161,2017
14153,13,1,1,0,0,0,0,0,0,34,1,555 168,BJ7,555,168,2017
14154,32,0,1,1,1,0,0,1,0,34,1,555 175,BJ7,555,175,2017
14155,21,0,1,1,0,0,0,1,0,34,1,555 183,BJ7,555,183,2017

In [22]:
benin['water_source'] = benin['water_source'].replace([10,11,12,13,14,20,21,30,31,41,51], 1)

In [23]:
benin['water_source'] = benin['water_source'].replace([32,40,42,43,61,62,71], 0)

In [24]:
benin['floor'].value_counts()

34    8630
11    4091
33     626
12     133
21      86
35      84
22      78
31      50
32      18
Name: floor, dtype: int64

In [25]:
benin['floor'] = benin['floor'].replace([11,12,21,22,], 0)

In [26]:
benin['floor'] = benin['floor'].replace([31,32,33,34,35], 1)

In [27]:
benin['floor'].value_counts()

1    9408
0    4388
Name: floor, dtype: int64

### Final state of the dataframe before doing PCA

In [28]:
benin

,water_source,toilet,Electricity,Radio,Television,Fridge,Bicycle,Motorbike,Car,floor,U1_R2,HHID,countrycode,cluster_number,household_number,Year
0,0,0,1,1,0,0,0,0,0,1,2,1 3,BJ7,1,3,2018
1,0,0,0,1,0,0,1,1,0,1,2,1 9,BJ7,1,9,2018
2,0,0,1,1,1,0,0,1,0,1,2,1 15,BJ7,1,15,2018
3,0,0,0,1,0,0,0,1,0,0,2,1 21,BJ7,1,21,2018
4,0,0,0,1,0,0,1,0,0,0,2,1 27,BJ7,1,27,2018
5,0,0,1,1,0,0,1,1,0,1,2,1 33,BJ7,1,33,2018
6,0,0,0,1,0,0,1,1,0,1,2,1 39,BJ7,1,39,2018
7,0,0,1,1,0,0,1,1,0,0,2,1 46,BJ7,1,46,2018
8,0,0,0,1,0,0,1,1,0,0,2,1 52,BJ7,1,52,2018
9,0,0,1,1,0,0,1,1,0,1,2,1 58,BJ7,1,58,2018
10,0,0,0,0,0,0,0,0,0,1,2,1 64,BJ7,1,64,2018
11,0,0,0,1,0,0,0,1,0,0,2,1 70,BJ7,1,70,2018
12,0,0,0,1,0,0,1,1,0,1,2,1 76,BJ7,1,76,2018
13,0,0,1,1,0,0,1,1,0,0,2,1 82,BJ7,1,82,2018
14,0,0,0,1,0,0,1,1,0,0,2,1 88,BJ7,1,88,2018
15,0,0,0,1,0,0,1,0,0,0,2,1 94,BJ7,1,94,2018
16,0,0,0,1,0,0,0,0,0,1,2,1 101,BJ7,1,101,2018
17,1,0,1,1,1,0,1,1,0,1,2,1 107,BJ7,1,107,2018
18,0,0,0,1,0,0,0,1,0,0,2,1 113,BJ7,1,113,2018
19,1,0,1,1,0,0,0,1,0,1,2,1 119,BJ7,1,119,2018
20,0,0,0,1,0,0,0,1,0,1,2,1 125,BJ7,1,125,2018
21,1,0,0,1,0,0,0,0,0,0,2,1 131,BJ7,1,131,2018
22,1,0,0,1,0,0,0,1,0,1,2,1 137,BJ7,1,137,2018
23,1,0,1,1,0,0,1,1,0,1,2,1 143,BJ7,1,143,2018
24,0,0,0,1,0,0,0,1,0,1,2,1 149,BJ7,1,149,2018
25,1,0,1,1,0,0,1,1,0,1,2,1 156,BJ7,1,156,2018
26,0,0,0,1,0,0,0,1,0,1,2,2 2,BJ7,2,2,2018
27,0,0,0,1,0,0,0,0,0,0,2,2 7,BJ7,2,7,2018
28,0,0,0,0,0,0,1,0,0,0,2,2 13,BJ7,2,13,2018
29,0,0,0,1,0,0,1,0,0,0,2,2 19,BJ7,2,19,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14126,1,0,0,1,1,0,0,1,0,1,2,554 108,BJ7,554,108,2017
14127,1,0,0,0,0,0,0,0,0,0,2,554 113,BJ7,554,113,2017
14128,1,0,0,1,0,0,1,1,0,0,2,554 118,BJ7,554,118,2017
14129,1,0,0,1,0,0,0,1,0,0,2,554 123,BJ7,554,123,2017
14130,1,0,0,1,0,0,0,1,0,1,2,554 128,BJ7,554,128,2017
14131,1,1,1,1,1,0,0,1,0,1,1,555 4,BJ7,555,4,2017
14132,1,1,1,1,1,0,0,1,0,1,1,555 11,BJ7,555,11,2017
14133,1,0,0,1,0,0,0,1,0,1,1,555 18,BJ7,555,18,2017
14134,1,1,0,1,1,0,0,1,0,1,1,555 25,BJ7,555,25,2017
14135,1,0,1,0,0,0,0,1,0,1,1,555 32,BJ7,555,32,2017
14136,1,0,0,1,0,0,0,0,0,1,1,555 39,BJ7,555,39,2017
14137,1,1,1,1,1,0,0,1,0,1,1,555 47,BJ7,555,47,2017
14138,1,1,1,1,0,0,0,1,0,1,1,555 54,BJ7,555,54,2017
14139,1,1,0,0,0,0,0,0,0,1,1,555 61,BJ7,555,61,2017
14140,1,1,1,1,1,0,0,0,0,1,1,555 68,BJ7,555,68,2017
14141,0,1,1,1,1,0,0,1,0,1,1,555 75,BJ7,555,75,2017
14142,1,0,1,1,1,0,0,1,0,1,1,555 82,BJ7,555,82,2017
14143,1,1,1,1,1,0,0,1,0,1,1,555 90,BJ7,555,90,2017
14144,1,1,1,1,1,1,1,1,1,1,1,555 97,BJ7,555,97,2017
14145,1,1,1,1,0,0,0,0,0,1,1,555 104,BJ7,555,104,2017
14146,1,0,1,0,1,0,1,1,0,1,1,555 111,BJ7,555,111,2017
14147,1,1,1,1,1,0,0,1,0,1,1,555 118,BJ7,555,118,2017
14148,0,0,0,1,1,0,0,1,0,0,1,555 132,BJ7,555,132,2017
14149,1,0,1,1,1,0,0,1,0,1,1,555 140,BJ7,555,140,2017
14150,1,1,1,1,1,0,0,1,0,1,1,555 147,BJ7,555,147,2017
14151,1,1,1,1,1,1,0,1,0,1,1,555 154,BJ7,555,154,2017
14152,0,1,1,1,1,0,0,1,0,1,1,555 161,BJ7,555,161,2017
14153,1,1,1,0,0,0,0,0,0,1,1,555 168,BJ7,555,168,2017
14154,0,0,1,1,1,0,0,1,0,1,1,555 175,BJ7,555,175,2017
14155,1,0,1,1,0,0,0,1,0,1,1,555 183,BJ7,555,183,2017

# PCA Part

In [29]:
import numpy
from sklearn.decomposition import PCA
from sklearn import preprocessing

### features variable contains the columns included in PCA

In [30]:
#benin.columns
features = ['water_source', 'toilet', 'Electricity', 'Radio', 'Television','Fridge', 'Bicycle', 'Motorbike', 'Car', 'floor']
info = ['HHID', 'year']

In [31]:
X = benin.loc[:, features].values
Y = benin.loc[:,info].values

D:\python\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

In [32]:
X = preprocessing.StandardScaler().fit_transform(X)

D:\python\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\python\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [33]:
pca = PCA(n_components = 1)

In [34]:
X_pca = pca.fit_transform(X)

In [35]:
print(pca.explained_variance_ratio_)

[0.30394726]

In [36]:
principalDf = pd.DataFrame(data = X_pca, columns = ['wealth_index'])

### Creating a dataframe with the newly calculated wealth index

In [37]:
final_benin = pd.concat([principalDf, benin[['HHID']], benin[['cluster_number']], benin[['household_number']], benin[['Year']]], axis = 1)
final_benin

       wealth_index          HHID  cluster_number  household_number    Year
0         -0.092185         1   3             1.0               3.0  2018.0
1         -0.763892         1   9             1.0               9.0  2018.0
2          1.315689         1  15             1.0              15.0  2018.0
3         -1.386124         1  21             1.0              21.0  2018.0
4         -1.900860         1  27             1.0              27.0  2018.0
5          0.190369         1  33             1.0              33.0  2018.0
6         -0.763892         1  39             1.0              39.0  2018.0
7         -0.547955         1  46             1.0              46.0  2018.0
8         -1.502216         1  52             1.0              52.0  2018.0
9          0.190369         1  58             1.0              58.0  2018.0
10        -1.604290         1  64             1.0              64.0  2018.0
11        -1.386124         1  70             1.0              70.0  2018.0
12        -0.763892         1  76             1.0              76.0  2018.0
13        -0.547955         1  82             1.0              82.0  2018.0
14        -1.502216         1  88             1.0              88.0  2018.0
15        -1.900860         1  94             1.0              94.0  2018.0
16        -1.046445         1 101             1.0             101.0  2018.0
17         1.617965         1 107             1.0             107.0  2018.0
18        -1.386124         1 113             1.0             113.0  2018.0
19         0.724827         1 119             1.0             119.0  2018.0
20        -0.647801         1 125             1.0             125.0  2018.0
21        -1.366402         1 131             1.0             131.0  2018.0
22        -0.229434         1 137             1.0             137.0  2018.0
23         0.608736         1 143             1.0             143.0  2018.0
24        -0.647801         1 149             1.0             149.0  2018.0
25         0.608736         1 156             1.0             156.0  2018.0
26        -0.647801         2   2             2.0               2.0  2018.0
27        -1.784769         2   7             2.0               7.0  2018.0
28        -2.458705         2  13             2.0              13.0  2018.0
29        -1.900860         2  19             2.0              19.0  2018.0
...             ...           ...             ...               ...     ...
14126           NaN       554 108           554.0             108.0  2017.0
14127           NaN       554 113           554.0             113.0  2017.0
14128           NaN       554 118           554.0             118.0  2017.0
14129           NaN       554 123           554.0             123.0  2017.0
14130           NaN       554 128           554.0             128.0  2017.0
14131           NaN       555   4           555.0               4.0  2017.0
14132           NaN       555  11           555.0              11.0  2017.0
14133           NaN       555  18           555.0              18.0  2017.0
14134           NaN       555  25           555.0              25.0  2017.0
14135           NaN       555  32           555.0              32.0  2017.0
14136           NaN       555  39           555.0              39.0  2017.0
14137           NaN       555  47           555.0              47.0  2017.0
14138           NaN       555  54           555.0              54.0  2017.0
14139           NaN       555  61           555.0              61.0  2017.0
14140           NaN       555  68           555.0              68.0  2017.0
14141           NaN       555  75           555.0              75.0  2017.0
14142           NaN       555  82           555.0              82.0  2017.0
14143           NaN       555  90           555.0              90.0  2017.0
14144           NaN       555  97           555.0              97.0  2017.0
14145           NaN       555 104           555.0             104.0  2017.0
14146           NaN       555 111           555.0             111.0  2017.0
14147           NaN       555 118           555.0             118.0  2017.0
14148           NaN       555 132           555.0             132.0  2017.0
14149           NaN       555 140           555.0             140.0  2017.0
14150           NaN       555 147           555.0             147.0  2017.0
14151           NaN       555 154           555.0             154.0  2017.0
14152           NaN       555 161           555.0             161.0  2017.0
14153           NaN       555 168           555.0             168.0  2017.0
14154           NaN       555 175           555.0             175.0  2017.0
14155           NaN       555 183           555.0             183.0  2017.0

[14147 rows x 5 columns]

In [38]:
final_benin.dropna(inplace=True)

In [39]:
final_benin.isna().sum()

wealth_index        0
HHID                0
cluster_number      0
household_number    0
Year                0
dtype: int64

In [68]:
final_benin.to_excel("Benin_18_wealth.xlsx")

### This creates a file that has wealth index grouped by cluster. Just what we want

In [69]:
wealth_index_2018 = final_benin.groupby('cluster_number')['wealth_index'].mean()

In [70]:
wealth_index_2018

cluster_number
1.0     -0.566530
2.0     -1.183113
3.0     -1.132137
4.0     -1.620975
5.0     -1.078353
6.0     -1.678663
7.0     -1.230599
8.0     -1.013078
9.0     -1.013501
10.0     0.470216
11.0     0.512325
12.0    -0.505712
13.0    -0.345122
14.0    -0.525047
15.0    -0.343963
16.0    -1.225512
17.0     0.731462
18.0     0.268525
19.0    -0.179119
20.0    -0.781140
21.0    -1.097504
22.0    -0.879744
23.0     0.396132
24.0     0.962063
25.0     1.469461
26.0    -0.015463
27.0    -1.415824
28.0    -1.934469
29.0    -1.631797
30.0    -1.446284
           ...
512.0   -0.666214
513.0    0.793302
514.0   -0.548834
515.0   -1.022225
516.0   -1.255862
517.0   -1.137933
518.0   -0.751954
519.0   -0.170907
520.0   -0.390732
521.0   -0.847413
522.0   -0.763326
523.0   -1.058914
524.0   -1.049394
525.0   -1.281342
526.0   -1.221956
527.0   -0.885290
528.0   -0.496668
529.0   -0.418965
530.0   -0.634048
531.0   -0.555397
532.0   -0.074339
533.0    0.049216
534.0   -1.001624
535.0   -0.737879
536.0   -0.793650
537.0    0.649122
538.0   -0.650727
539.0   -0.714821
540.0   -1.064082
541.0    1.634776
Name: wealth_index, Length: 541, dtype: float64

In [120]:
wealth_index_2018.to_excel("wealth_index_2018.xlsx")

In [87]:
benin2012 = pd.read_excel("Benin_12.xlsx")
benin2012

,water_source,toilet,Electricity,Radio,Television,Fridge,Bicycle,Motorbike,Car,floor,U1_R2,HHID,countrycode,cluster_number,household_number,Year
0,13,43,0,1,0,0,1,1,0,11,1,1 1,BJ6,1,1,2012
1,13,31,0,0,0,0,1,1,0,11,1,1 2,BJ6,1,2,2012
2,21,23,0,1,0,0,1,1,0,34,1,1 3,BJ6,1,3,2012
3,13,43,0,0,0,0,1,1,0,11,1,1 4,BJ6,1,4,2012
4,13,43,0,0,0,0,1,1,0,11,1,1 5,BJ6,1,5,2012
5,21,31,0,1,0,0,0,0,0,34,1,1 6,BJ6,1,6,2012
6,13,43,0,1,0,0,1,1,0,11,1,1 7,BJ6,1,7,2012
7,32,31,0,1,0,0,1,0,0,11,1,1 8,BJ6,1,8,2012
8,13,31,0,1,0,0,1,0,0,11,1,1 9,BJ6,1,9,2012
9,32,31,0,1,0,0,1,0,0,11,1,1 10,BJ6,1,10,2012
10,13,43,0,1,1,0,1,1,0,34,1,1 11,BJ6,1,11,2012
11,21,31,0,1,0,0,1,1,0,11,1,1 13,BJ6,1,13,2012
12,21,31,0,0,0,0,1,0,0,11,1,1 14,BJ6,1,14,2012
13,32,31,0,1,0,0,0,1,0,11,1,1 15,BJ6,1,15,2012
14,21,31,0,0,0,0,0,0,0,11,1,1 16,BJ6,1,16,2012
15,31,31,0,0,0,0,1,1,0,11,1,1 17,BJ6,1,17,2012
16,21,31,0,1,0,0,1,1,0,34,1,1 18,BJ6,1,18,2012
17,32,31,0,0,0,0,1,0,0,11,1,1 19,BJ6,1,19,2012
18,21,31,0,1,0,0,1,0,0,11,1,1 21,BJ6,1,21,2012
19,21,31,0,1,0,0,1,1,0,11,1,1 22,BJ6,1,22,2012
20,13,31,0,1,0,0,1,0,0,11,1,1 23,BJ6,1,23,2012
21,21,22,0,1,1,1,0,1,0,34,1,1 24,BJ6,1,24,2012
22,32,31,1,1,1,0,0,1,0,34,1,2 1,BJ6,2,1,2012
23,13,43,1,0,1,0,1,1,0,34,1,2 2,BJ6,2,2,2012
24,31,23,1,1,1,0,0,1,0,34,1,2 3,BJ6,2,3,2012
25,13,31,1,1,1,0,0,1,0,34,1,2 4,BJ6,2,4,2012
26,32,31,1,1,1,0,1,0,0,34,1,2 6,BJ6,2,6,2012
27,13,43,1,1,1,0,0,1,0,34,1,2 7,BJ6,2,7,2012
28,13,43,1,1,1,0,0,1,0,34,1,2 8,BJ6,2,8,2012
29,32,31,0,0,0,0,1,1,0,34,1,2 10,BJ6,2,10,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12295,11,22,1,1,0,0,0,0,0,34,1,531 8,BJ6,531,8,2012
12296,13,22,1,1,1,0,0,1,0,34,1,531 10,BJ6,531,10,2012
12297,12,22,1,1,1,0,0,1,0,34,1,531 11,BJ6,531,11,2012
12298,11,31,1,1,1,0,0,0,0,34,1,531 12,BJ6,531,12,2012
12299,11,22,1,1,1,0,0,0,0,34,1,531 13,BJ6,531,13,2012
12300,11,22,1,1,0,0,0,0,0,34,1,531 14,BJ6,531,14,2012
12301,12,31,1,1,0,0,0,0,0,34,1,531 15,BJ6,531,15,2012
12302,11,22,1,1,0,0,0,0,0,34,1,531 16,BJ6,531,16,2012
12303,11,22,1,1,1,0,0,1,0,34,1,531 17,BJ6,531,17,2012
12304,12,21,1,1,0,0,0,0,0,34,1,531 18,BJ6,531,18,2012
12305,11,23,1,1,1,0,1,0,0,34,1,531 19,BJ6,531,19,2012
12306,11,22,1,1,1,0,0,1,0,34,1,531 20,BJ6,531,20,2012
12307,12,31,1,1,1,0,0,1,0,34,1,531 21,BJ6,531,21,2012
12308,11,23,1,1,1,0,0,1,0,34,1,531 22,BJ6,531,22,2012
12309,11,11,1,1,1,1,1,1,0,34,1,531 23,BJ6,531,23,2012
12310,12,22,1,1,1,0,0,1,0,34,1,531 24,BJ6,531,24,2012
12311,11,22,1,1,1,0,0,0,0,34,1,532 1,BJ6,532,1,2012
12312,11,41,1,1,1,0,0,0,0,34,1,532 2,BJ6,532,2,2012
12313,12,12,1,1,1,0,0,0,0,34,1,532 3,BJ6,532,3,2012
12314,11,41,1,1,1,1,0,0,0,34,1,532 4,BJ6,532,4,2012
12315,11,23,1,1,1,0,0,0,0,34,1,532 5,BJ6,532,5,2012
12316,12,13,0,1,0,0,0,0,0,34,1,532 6,BJ6,532,6,2012
12317,11,22,1,1,1,1,0,0,1,34,1,532 7,BJ6,532,7,2012
12318,11,22,1,1,1,0,0,1,0,34,1,532 8,BJ6,532,8,2012
12319,12,12,0,0,0,0,0,0,0,34,1,532 9,BJ6,532,9,2012
12320,11,22,1,0,0,0,0,1,0,34,1,532 10,BJ6,532,10,2012
12321,13,22,1,1,1,0,0,0,0,34,1,532 11,BJ6,532,11,2012
12322,12,22,1,1,0,0,0,0,0,34,1,532 12,BJ6,532,12,2012
12323,11,22,1,1,1,1,0,1,0,34,1,532 13,BJ6,532,13,2012
12324,11,12,1,1,1,1,0,0,0,34,1,532 14,BJ6,532,14,2012

In [89]:
to_drop2012 = benin2012[ (benin2012['water_source'] == 96) | (benin2012['toilet'] == 96) | (benin2012['floor'] == 96)].index
to_drop2012_2 = benin2012[ benin2012['toilet'] == 13 ].index
to_drop2012_3 = benin2012[ benin2012['water_source'] == 72 ].index

In [99]:
benin2012.drop(to_drop2012, inplace = True)
benin2012.drop(to_drop2012_2, inplace = True)
benin2012.drop(to_drop2012_3, inplace = True)

In [100]:
benin2012

,water_source,toilet,Electricity,Radio,Television,Fridge,Bicycle,Motorbike,Car,floor,U1_R2,HHID,countrycode,cluster_number,household_number,Year
0,13,43,0,1,0,0,1,1,0,11,1,1 1,BJ6,1,1,2012
1,13,31,0,0,0,0,1,1,0,11,1,1 2,BJ6,1,2,2012
2,21,23,0,1,0,0,1,1,0,34,1,1 3,BJ6,1,3,2012
3,13,43,0,0,0,0,1,1,0,11,1,1 4,BJ6,1,4,2012
4,13,43,0,0,0,0,1,1,0,11,1,1 5,BJ6,1,5,2012
5,21,31,0,1,0,0,0,0,0,34,1,1 6,BJ6,1,6,2012
6,13,43,0,1,0,0,1,1,0,11,1,1 7,BJ6,1,7,2012
7,32,31,0,1,0,0,1,0,0,11,1,1 8,BJ6,1,8,2012
8,13,31,0,1,0,0,1,0,0,11,1,1 9,BJ6,1,9,2012
9,32,31,0,1,0,0,1,0,0,11,1,1 10,BJ6,1,10,2012
10,13,43,0,1,1,0,1,1,0,34,1,1 11,BJ6,1,11,2012
11,21,31,0,1,0,0,1,1,0,11,1,1 13,BJ6,1,13,2012
12,21,31,0,0,0,0,1,0,0,11,1,1 14,BJ6,1,14,2012
13,32,31,0,1,0,0,0,1,0,11,1,1 15,BJ6,1,15,2012
14,21,31,0,0,0,0,0,0,0,11,1,1 16,BJ6,1,16,2012
15,31,31,0,0,0,0,1,1,0,11,1,1 17,BJ6,1,17,2012
16,21,31,0,1,0,0,1,1,0,34,1,1 18,BJ6,1,18,2012
17,32,31,0,0,0,0,1,0,0,11,1,1 19,BJ6,1,19,2012
18,21,31,0,1,0,0,1,0,0,11,1,1 21,BJ6,1,21,2012
19,21,31,0,1,0,0,1,1,0,11,1,1 22,BJ6,1,22,2012
20,13,31,0,1,0,0,1,0,0,11,1,1 23,BJ6,1,23,2012
21,21,22,0,1,1,1,0,1,0,34,1,1 24,BJ6,1,24,2012
22,32,31,1,1,1,0,0,1,0,34,1,2 1,BJ6,2,1,2012
23,13,43,1,0,1,0,1,1,0,34,1,2 2,BJ6,2,2,2012
24,31,23,1,1,1,0,0,1,0,34,1,2 3,BJ6,2,3,2012
25,13,31,1,1,1,0,0,1,0,34,1,2 4,BJ6,2,4,2012
26,32,31,1,1,1,0,1,0,0,34,1,2 6,BJ6,2,6,2012
27,13,43,1,1,1,0,0,1,0,34,1,2 7,BJ6,2,7,2012
28,13,43,1,1,1,0,0,1,0,34,1,2 8,BJ6,2,8,2012
29,32,31,0,0,0,0,1,1,0,34,1,2 10,BJ6,2,10,2012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12294,11,23,1,1,1,0,0,1,0,34,1,531 7,BJ6,531,7,2012
12295,11,22,1,1,0,0,0,0,0,34,1,531 8,BJ6,531,8,2012
12296,13,22,1,1,1,0,0,1,0,34,1,531 10,BJ6,531,10,2012
12297,12,22,1,1,1,0,0,1,0,34,1,531 11,BJ6,531,11,2012
12298,11,31,1,1,1,0,0,0,0,34,1,531 12,BJ6,531,12,2012
12299,11,22,1,1,1,0,0,0,0,34,1,531 13,BJ6,531,13,2012
12300,11,22,1,1,0,0,0,0,0,34,1,531 14,BJ6,531,14,2012
12301,12,31,1,1,0,0,0,0,0,34,1,531 15,BJ6,531,15,2012
12302,11,22,1,1,0,0,0,0,0,34,1,531 16,BJ6,531,16,2012
12303,11,22,1,1,1,0,0,1,0,34,1,531 17,BJ6,531,17,2012
12304,12,21,1,1,0,0,0,0,0,34,1,531 18,BJ6,531,18,2012
12305,11,23,1,1,1,0,1,0,0,34,1,531 19,BJ6,531,19,2012
12306,11,22,1,1,1,0,0,1,0,34,1,531 20,BJ6,531,20,2012
12307,12,31,1,1,1,0,0,1,0,34,1,531 21,BJ6,531,21,2012
12308,11,23,1,1,1,0,0,1,0,34,1,531 22,BJ6,531,22,2012
12309,11,11,1,1,1,1,1,1,0,34,1,531 23,BJ6,531,23,2012
12310,12,22,1,1,1,0,0,1,0,34,1,531 24,BJ6,531,24,2012
12311,11,22,1,1,1,0,0,0,0,34,1,532 1,BJ6,532,1,2012
12312,11,41,1,1,1,0,0,0,0,34,1,532 2,BJ6,532,2,2012
12313,12,12,1,1,1,0,0,0,0,34,1,532 3,BJ6,532,3,2012
12314,11,41,1,1,1,1,0,0,0,34,1,532 4,BJ6,532,4,2012
12315,11,23,1,1,1,0,0,0,0,34,1,532 5,BJ6,532,5,2012
12317,11,22,1,1,1,1,0,0,1,34,1,532 7,BJ6,532,7,2012
12318,11,22,1,1,1,0,0,1,0,34,1,532 8,BJ6,532,8,2012
12319,12,12,0,0,0,0,0,0,0,34,1,532 9,BJ6,532,9,2012
12320,11,22,1,0,0,0,0,1,0,34,1,532 10,BJ6,532,10,2012
12321,13,22,1,1,1,0,0,0,0,34,1,532 11,BJ6,532,11,2012
12322,12,22,1,1,0,0,0,0,0,34,1,532 12,BJ6,532,12,2012
12323,11,22,1,1,1,1,0,1,0,34,1,532 13,BJ6,532,13,2012
12324,11,12,1,1,1,1,0,0,0,34,1,532 14,BJ6,532,14,2012

In [104]:
benin2012['toilet'] = benin2012['toilet'].replace([10,11,12,14,15,20,21,22], 1)
benin2012['toilet'] = benin2012['toilet'].replace([23,30,31,41,42,43], 0)

In [105]:
benin2012['water_source'] = benin2012['water_source'].replace([10,11,12,13,14,20,21,30,31,41,51], 1)
benin2012['water_source'] = benin2012['water_source'].replace([32,40,42,43,61,62,71], 0)

In [109]:
benin2012['floor'].value_counts()

1    7030
0    5168
Name: floor, dtype: int64

In [116]:
final_benin_2012.dropna(inplace=True)

In [106]:
benin2012['floor'] = benin2012['floor'].replace([11,12,21,22,], 0)
benin2012['floor'] = benin2012['floor'].replace([31,32,33,34,35], 1)

In [111]:
X2012 = benin2012.loc[:, features].values
Y2012 = benin2012.loc[:,info].values

D:\python\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

In [112]:
X_2012 = preprocessing.StandardScaler().fit_transform(X2012)

D:\python\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
D:\python\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

In [113]:
X_2012_pca = pca.fit_transform(X_2012)

In [114]:
principalDf_2012 = pd.DataFrame(data = X_2012_pca, columns = ['wealth_index'])

In [115]:
final_benin_2012 = pd.concat([principalDf_2012, benin2012[['HHID']], benin2012[['cluster_number']], benin2012[['household_number']], benin2012[['Year']]], axis = 1)
final_benin_2012

       wealth_index          HHID  cluster_number  household_number    Year
0         -1.220223          1  1             1.0               1.0  2012.0
1         -1.701185          1  2             1.0               2.0  2012.0
2         -0.491925          1  3             1.0               3.0  2012.0
3         -1.701185          1  4             1.0               4.0  2012.0
4         -1.701185          1  5             1.0               5.0  2012.0
5         -0.561471          1  6             1.0               6.0  2012.0
6         -1.220223          1  7             1.0               7.0  2012.0
7         -2.044506          1  8             1.0               8.0  2012.0
8         -1.614736          1  9             1.0               9.0  2012.0
9         -2.044506          1 10             1.0              10.0  2012.0
10         0.479671          1 11             1.0              11.0  2012.0
11        -1.220223          1 13             1.0              13.0  2012.0
12        -2.095697          1 14             1.0              14.0  2012.0
13        -1.325027          1 15             1.0              15.0  2012.0
14        -1.770731          1 16             1.0              16.0  2012.0
15        -1.701185          1 17             1.0              17.0  2012.0
16        -0.491925          1 18             1.0              18.0  2012.0
17        -2.525467          1 19             1.0              19.0  2012.0
18        -1.614736          1 21             1.0              21.0  2012.0
19        -1.220223          1 22             1.0              22.0  2012.0
20        -1.614736          1 23             1.0              23.0  2012.0
21         2.913765          1 24             1.0              24.0  2012.0
22         1.337179          2  1             2.0               1.0  2012.0
23         0.961021          2  2             2.0               2.0  2012.0
24         1.766949          2  3             2.0               3.0  2012.0
25         1.766949          2  4             2.0               4.0  2012.0
26         0.617700          2  6             2.0               6.0  2012.0
27         1.766949          2  7             2.0               7.0  2012.0
28         1.766949          2  8             2.0               8.0  2012.0
29        -1.402657          2 10             2.0              10.0  2012.0
...             ...           ...             ...               ...     ...
12294           NaN        531  7           531.0               7.0  2012.0
12295           NaN        531  8           531.0               8.0  2012.0
12296           NaN        531 10           531.0              10.0  2012.0
12297           NaN        531 11           531.0              11.0  2012.0
12298           NaN        531 12           531.0              12.0  2012.0
12299           NaN        531 13           531.0              13.0  2012.0
12300           NaN        531 14           531.0              14.0  2012.0
12301           NaN        531 15           531.0              15.0  2012.0
12302           NaN        531 16           531.0              16.0  2012.0
12303           NaN        531 17           531.0              17.0  2012.0
12304           NaN        531 18           531.0              18.0  2012.0
12305           NaN        531 19           531.0              19.0  2012.0
12306           NaN        531 20           531.0              20.0  2012.0
12307           NaN        531 21           531.0              21.0  2012.0
12308           NaN        531 22           531.0              22.0  2012.0
12309           NaN        531 23           531.0              23.0  2012.0
12310           NaN        531 24           531.0              24.0  2012.0
12311           NaN        532  1           532.0               1.0  2012.0
12312           NaN        532  2           532.0               2.0  2012.0
12313           NaN        532  3           532.0               3.0  2012.0
12314           NaN        532  4           532.0               4.0  2012.0
12315           NaN        532  5           532.0               5.0  2012.0
12317           NaN        532  7           532.0               7.0  2012.0
12318           NaN        532  8           532.0               8.0  2012.0
12319           NaN        532  9           532.0               9.0  2012.0
12320           NaN        532 10           532.0              10.0  2012.0
12321           NaN        532 11           532.0              11.0  2012.0
12322           NaN        532 12           532.0              12.0  2012.0
12323           NaN        532 13           532.0              13.0  2012.0
12324           NaN        532 14           532.0              14.0  2012.0

[12324 rows x 5 columns]

In [117]:
final_benin_2012

       wealth_index          HHID  cluster_number  household_number    Year
0         -1.220223          1  1             1.0               1.0  2012.0
1         -1.701185          1  2             1.0               2.0  2012.0
2         -0.491925          1  3             1.0               3.0  2012.0
3         -1.701185          1  4             1.0               4.0  2012.0
4         -1.701185          1  5             1.0               5.0  2012.0
5         -0.561471          1  6             1.0               6.0  2012.0
6         -1.220223          1  7             1.0               7.0  2012.0
7         -2.044506          1  8             1.0               8.0  2012.0
8         -1.614736          1  9             1.0               9.0  2012.0
9         -2.044506          1 10             1.0              10.0  2012.0
10         0.479671          1 11             1.0              11.0  2012.0
11        -1.220223          1 13             1.0              13.0  2012.0
12        -2.095697          1 14             1.0              14.0  2012.0
13        -1.325027          1 15             1.0              15.0  2012.0
14        -1.770731          1 16             1.0              16.0  2012.0
15        -1.701185          1 17             1.0              17.0  2012.0
16        -0.491925          1 18             1.0              18.0  2012.0
17        -2.525467          1 19             1.0              19.0  2012.0
18        -1.614736          1 21             1.0              21.0  2012.0
19        -1.220223          1 22             1.0              22.0  2012.0
20        -1.614736          1 23             1.0              23.0  2012.0
21         2.913765          1 24             1.0              24.0  2012.0
22         1.337179          2  1             2.0               1.0  2012.0
23         0.961021          2  2             2.0               2.0  2012.0
24         1.766949          2  3             2.0               3.0  2012.0
25         1.766949          2  4             2.0               4.0  2012.0
26         0.617700          2  6             2.0               6.0  2012.0
27         1.766949          2  7             2.0               7.0  2012.0
28         1.766949          2  8             2.0               8.0  2012.0
29        -1.402657          2 10             2.0              10.0  2012.0
...             ...           ...             ...               ...     ...
12168      1.766949        525 20           525.0              20.0  2012.0
12169      1.318404        525 21           525.0              21.0  2012.0
12170      2.684512        525 23           525.0              23.0  2012.0
12171      2.684512        525 24           525.0              24.0  2012.0
12172      1.372437        526  1           526.0               1.0  2012.0
12173      2.290000        526  2           526.0               2.0  2012.0
12174      1.318404        526  3           526.0               3.0  2012.0
12175      0.400841        526  4           526.0               4.0  2012.0
12176      1.318404        526  5           526.0               5.0  2012.0
12177      2.684512        526  6           526.0               6.0  2012.0
12178      1.318404        526  8           526.0               8.0  2012.0
12179      1.047470        526  9           526.0               9.0  2012.0
12180      2.684512        526 10           526.0              10.0  2012.0
12181      1.766949        526 11           526.0              11.0  2012.0
12182      1.766949        526 12           526.0              12.0  2012.0
12183      3.551110        526 13           526.0              13.0  2012.0
12184      2.684512        526 14           526.0              14.0  2012.0
12185      2.290000        526 15           526.0              15.0  2012.0
12186      1.372437        526 16           526.0              16.0  2012.0
12187      2.290000        526 17           526.0              17.0  2012.0
12188      2.564001        526 18           526.0              18.0  2012.0
12189      1.372437        526 19           526.0              19.0  2012.0
12190      4.640152        526 20           526.0              20.0  2012.0
12191      2.684512        526 21           526.0              21.0  2012.0
12192     -0.124870        526 22           526.0              22.0  2012.0
12193      1.231955        527  1           527.0               1.0  2012.0
12194      2.290000        527  2           527.0               2.0  2012.0
12195      1.318404        527  3           527.0               3.0  2012.0
12196      3.876077        527  4           527.0               4.0  2012.0
12197      3.481564        527  5           527.0               5.0  2012.0

[12072 rows x 5 columns]

In [118]:
wealth_index_2012 = final_benin_2012.groupby('cluster_number')['wealth_index'].mean()

In [119]:
wealth_index_2012

cluster_number
1.0     -1.203984
2.0      0.775456
3.0     -1.154778
4.0     -1.085995
5.0     -0.867723
6.0     -1.477563
7.0     -1.439313
8.0     -1.599895
9.0     -1.152433
10.0    -1.589698
11.0    -1.729288
12.0     0.873968
13.0    -1.363681
14.0    -0.668433
15.0    -1.461159
16.0    -0.885412
17.0    -1.112059
18.0    -0.990293
19.0     1.398608
20.0    -0.558374
21.0    -1.167879
22.0    -1.278617
23.0    -1.418588
24.0    -0.738625
25.0    -0.867017
26.0    -1.189247
27.0    -1.954637
28.0    -1.892149
29.0    -1.858586
30.0    -1.365676
           ...
498.0   -1.084795
499.0   -1.126326
500.0   -1.351614
501.0   -0.831030
502.0   -0.004521
503.0    0.364236
504.0    0.868408
505.0    0.479962
506.0   -0.334928
507.0   -1.036153
508.0   -0.893610
509.0   -0.305471
510.0   -0.256046
511.0    0.706475
512.0   -0.766027
513.0   -0.891439
514.0   -1.266193
515.0   -0.278582
516.0   -0.065723
517.0   -1.105521
518.0   -1.153012
519.0   -1.315876
520.0   -0.834959
521.0   -0.012592
522.0    0.804645
523.0   -0.427354
524.0    0.447382
525.0    0.838710
526.0    1.966341
527.0    2.439600
Name: wealth_index, Length: 527, dtype: float64

In [121]:
wealth_index_2012.to_excel("wealth_index_2012.xlsx")